version: "3.8"
services:
  ecattle-mongo:
    image: mongo
    ports: 
      - ${MONGO_PORT}:27017
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == worker]
  ecattle-redis:
    image: redis:alpine
    ports:
      - ${REDIS_PORT}:6379
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == worker]
  ecattle-kernel:
    command: ["sh", "-c", "npm i & npm run start"]
    image: ecattle/kernel-bigboxx:latest
    ports:
      - ${KERNEL_PORT}:3000
    environment:
      - DB_CLOUD=mongodb://ecattle-mongo/e-cattle
      - REDIS_CLOUD=ecattle-redis
      - API_CLOUD=ecattle-cloud
      - CODE_FARM=${CODE_FARM}
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == worker]